### ISSUE TITLE
file missing for 001_Wavelength_calibration

### ISSUE THREAD

**Issue by ABooth494** [hpparvi/Parviainen-2015-TrES-3b-OSIRIS#3]
In [43]:

with open('results/wl_calibration.pkl', 'w') as f:
    dump(dict(ccd1=ccd1f.wlf.solution,
##               ccd2=ccd2f.wlf.solution), f)

IOError                                   Traceback (most recent call last)
<ipython-input-43-65f235500361> in <module>()
----> 1 with open('results/wl_calibration.pkl', 'w') as f:
      2     dump(dict(ccd1=ccd1f.wlf.solution,
      3               ccd2=ccd2f.wlf.solution), f)

IOError: [Errno 2] No such file or directory: 'results/wl_calibration.pkl'

**Comment by hpparvi** [comment]
The problem was that I had forgotten to add an empty "results" directory. This is now fixed.
