### ISSUE TITLE
002_Light_curve_creation ValueError

### ISSUE THREAD

**Issue by MantasAbazorius** [hpparvi/Parviainen-2015-TrES-3b-OSIRIS#5]
## For code block 19 "Write the light curves and the auxiliary data into a HDF5 file"

ValueError                                Traceback (most recent call last)
<ipython-input-19-0b3361e2c981> in <module>()
      8 hdf.put('final/bb_nomask',     DF(lc_bb_nomask,   *_bbargs), format='table', data_columns=True)
      9 hdf.put('final/bb_masked',     DF(lc_bb_masked,   *_bbargs), format='table', data_columns=True)
---> 10 hdf.put('final/nb_nomask',     DF(lc_nb_nomask,   *_nbargs), format='table', data_columns=True)
     11 hdf.put('final/nb_masked',     DF(lc_nb_masked,   *_nbargs), format='table', data_columns=True)
     12 hdf.put('target/bb_nomask',    DF(lc_bb_2_nomask, **bbargs), format='table', data_columns=True)

/home/mert3269/Library/Python/2.7/lib/python/site-packages/pandas/io/pytables.pyc in put(self, key, value, format, append, *_kwargs)
    817             format = get_option("io.hdf.default_format") or 'fixed'
    818         kwargs = self._validate_format(format, kwargs)
--> 819         self._write_to_group(key, value, append=append, *_kwargs)
    820 
    821     def remove(self, key, where=None, start=None, stop=None):

/home/mert3269/Library/Python/2.7/lib/python/site-packages/pandas/io/pytables.pyc in _write_to_group(self, key, value, format, index, append, complib, encoding, *_kwargs)
   1266 
   1267         # write the object
-> 1268         s.write(obj=value, append=append, complib=complib, *_kwargs)
   1269 
   1270         if s.is_table and index:

/home/mert3269/Library/Python/2.7/lib/python/site-packages/pandas/io/pytables.pyc in write(self, obj, axes, append, complib, complevel, fletcher32, min_itemsize, chunksize, expectedrows, dropna, **kwargs)
   3776 
   3777         for a in self.axes:
-> 3778             a.validate(self, append)
   3779 
   3780         if not self.is_exists:

/home/mert3269/Library/Python/2.7/lib/python/site-packages/pandas/io/pytables.pyc in validate(self, handler, append, *_kwargs)
   1545 
   1546     def validate(self, handler, append, *_kwargs):
-> 1547         self.validate_names()
   1548 
   1549     def validate_names(self):

/home/mert3269/Library/Python/2.7/lib/python/site-packages/pandas/io/pytables.pyc in validate_names(self)
   2097     def validate_names(self):
   2098         if not Index(self.values).is_object():
-> 2099             raise ValueError("cannot have non-object label DataIndexableCol")
   2100 
   2101     def get_atom_string(self, block, itemsize):

ValueError: cannot have non-object label DataIndexableCol

**Comment by hpparvi** [comment]
This was a problem with the new version of Pandas and PyTables, fixed.
