### ISSUE TITLE
Error in In[2] when trying to run 003_contamination

### ISSUE THREAD

**Issue by ABooth494** [hpparvi/Parviainen-2015-TrES-3b-OSIRIS#6]
ImportError                               Traceback (most recent call last)
<ipython-input-2-4d37bd7f6581> in <module>()
      3 from scipy.optimize import fmin
      4 
----> 5 from pyfc import psf_g1d
      6 from core import *
      7 

ImportError: No module named pyfc

**Comment by MantasAbazorius** [comment]
This is resolved if we import psf_gld from pycntr rather than pyfc.

**Comment by hpparvi** [comment]
Pull the latest version of PyCentroid and reinstall it. I changed the name of the package to pyfc at one point (yep...) but forgot to push the changes...
