### ISSUE TITLE
ldtk in 003a_bb_wn

### ISSUE THREAD

**Issue by MantasAbazorius** [hpparvi/Parviainen-2015-TrES-3b-OSIRIS#7]
## I have PyLDTk installed, but I'm not able to import it (there is some issue with RegularGridInterpolator)

ImportError                               Traceback (most recent call last)
<ipython-input-2-68a353618308> in <module>()
      8 from pyde.de import DiffEvol
      9 
---> 10 from lpf_ww import LPFunction
     11 from core import *
     12 

/home/mert3269/soft/Parviainen-2015-TrES-3b-OSIRIS/lpf_ww.py in <module>()
      5 
      6 from pytransit import MandelAgol as MA
----> 7 from ldtk import LDPSetCreator
      8 from exotk.priors import UP, NP, PriorSet
      9 from exotk.utils.orbits import as_from_rhop

/home/mert3269/Library/Python/2.7/lib/python/site-packages/ldtk/**init**.py in <module>()
----> 1 from ldtk import LDPSetCreator, LDPSet
      2 from filters import BoxcarFilter, TabulatedFilter
      3 
      4 **all** = ['LDPSetCreator','LDPSet','BoxcarFilter','TabulatedFilter','ldtk_cache','ldtk_root']

/home/mert3269/Library/Python/2.7/lib/python/site-packages/ldtk/ldtk.py in <module>()
     30                    diag, poly1d, polyfit, vstack, diff, cov, exp, log, sqrt, clip, pi)
     31 from numpy.random import normal, uniform, multivariate_normal
---> 32 from scipy.interpolate import RegularGridInterpolator as RGI
     33 from scipy.interpolate import interp1d
     34 from scipy.optimize import fmin

ImportError: cannot import name RegularGridInterpolator

**Comment by hpparvi** [comment]
You need to upgrade your SciPy.
