### ISSUE TITLE
003_contamination

### ISSUE THREAD

**Issue by MantasAbazorius** [hpparvi/Parviainen-2015-TrES-3b-OSIRIS#8]
In the 4th code block:
      files = sorted(glob(join(datadir,'object','*.fits')))[3:]
##       gain = pf.getval(files[0], 'gain', ext=0)

IndexError                                Traceback (most recent call last)
<ipython-input-4-d502b9cd2b07> in <module>()
      1 files = sorted(glob(join(datadir,'object','*.fits')))[3:]
----> 2 gain = pf.getval(files[0], 'gain', ext=0)

IndexError: list index out of range

**Comment by hpparvi** [comment]
Fixed: changed to use the example frame included in the data directory.
